### ISSUE TITLE
Use /usr/bin/env instead of /usr/bin/bash

### ISSUE THREAD

**Issue by jamessan** [hardenedapple/vsh#23]
On all the Linux systems I have access to, bash is installed as `/bin/bash`.  The bash scripts in vsh all have `/usr/bin/bash` in their shebang, so none of them work.

I expect that `/usr/bin/env` is a more standard location and also means that bash is found in `$PATH`, which better honors the user's expectations.

**Comment by hardenedapple** [comment]
Thanks!
Sounds like a good idea to me.

FYI it will be a while until I make the change, I'm on a cycle tour until
November and only have spotty internet access via phone.


On 20 Sep 2017 3:48 a.m., "James McCoy" <notifications@github.com> wrote:

On all the Linux systems I have access to, bash is installed as /bin/bash.
The bash scripts in vsh all have /usr/bin/bash in their shebang, so none of
them work.

I expect that /usr/bin/env is a more standard location and also means that
bash is found in $PATH, which better honors the user's expectations.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hardenedapple/vsh/issues/23>, or mute the thread
